### ISSUE TITLE
selene is not compatible with remote workspaces

### ISSUE THREAD

**Issue by preindex** [Kampfkarren/selene#349] opened 2022-03-18 02:12 UTC
When using Github Repositories I get this error, and no lint appears -
![Code_HFfFIYVVwS](https://user-images.githubusercontent.com/48609126/158923715-33dc5ee3-659c-4064-8e97-100478378983.png)

When I try Live Share, I get this:
![Code_b6dwfDZc90](https://user-images.githubusercontent.com/48609126/158924067-6922522d-abee-4b2e-a3c0-31d61f4f7fe6.png)
Not only will I get this, it won't respect the configuration already inside the remote workspace.
It's worth mentioning that when disabling the VSC extension, the linting and error checking is automatically done by the host.

**Comment by Kampfkarren** [comment] 2022-03-18 05:25
Duplicate of #159

**Closed by Kampfkarren** 2022-03-18 05:25 UTC
