### ISSUE TITLE
Selene incorrectly lints for unused variable for Luau types

### ISSUE THREAD

**Issue by bubshayz** [Kampfkarren/selene#450] opened 2022-10-23 21:17 UTC
Consider the following Luau code:

```lua
local a =  {} -- unused variable, marked by selene
type b = typeof(a)
local t : b = {}
print(t)
```

Selene will incorrectly mark `a` as unused, since it fails to see that it is used in a type!

**Comment by Kampfkarren** [comment] 2022-10-23 21:41
Duplicate of https://github.com/Kampfkarren/selene/issues/337

**Closed by Kampfkarren** 2022-10-23 21:41 UTC
