### ISSUE TITLE
Bug: Roblox instance.new errors when 2 arguments are provided

### ISSUE THREAD

**Issue by Milo123459** [Kampfkarren/selene#280] opened 2021-08-01 02:21 UTC
```lua
local Time = Instance.new("NumberValue", ls)
```
This code works, but selene thinks it's an error. The error is "required 1 arguments, got 2"

**Comment by Kampfkarren** [comment] 2021-08-01 18:09
Not a bug. Duplicate of #114, #115, and #121. 

Read https://github.com/Kampfkarren/selene/issues/114#issuecomment-637844358 for the answer on why.

**Closed by Kampfkarren** 2021-08-01 18:09 UTC
