### ISSUE TITLE
standard library function `Instance.new` requires 1 parameters, 2 passed

### ISSUE THREAD

**Issue by notsa-7** [Kampfkarren/selene#121] opened 2020-06-22 20:45 UTC
Instance.new takes to parameters, the second one being the parent object.

**Comment by Kampfkarren** [comment] 2020-06-22 20:56
Not a bug. Duplicate of #114 and #115. 

Read https://github.com/Kampfkarren/selene/issues/114#issuecomment-637844358 for the answer on why.

**Closed by Kampfkarren** 2020-06-22 20:56 UTC
