### ISSUE TITLE
Instance.new second argument missing

### ISSUE THREAD

**Issue by EpixScripts** [Kampfkarren/selene#378] opened 2022-06-18 07:07 UTC
In the Roblox standard, writing code such as
```lua
Instance.new("Part", Workspace)
```
will error, saying that the function requires 1 parameter, while I passed two. The second argument should be the optional parent argument.

**Comment by Kampfkarren** [comment] 2022-06-18 07:36
Duplicate of #114, #115, #121, #280. Read https://github.com/Kampfkarren/selene/issues/114#issuecomment-637844358 for why.

**Closed by Kampfkarren** 2022-06-18 07:37 UTC
