### ISSUE TITLE
Vector3.yAxis does not contain the field `Cross`

### ISSUE THREAD

**Issue by Pr0pelled** [Kampfkarren/selene#571] opened 2023-11-12 17:52 UTC
Highlights `Vector3.yAxis:Cross()` with the error: 
```
standard library global `Vector3.yAxis` does not contain the field `Cross`selene::incorrect_standard_library_use
```

I am using the VSCode extension version of selene (currently on v1.2.0), `selene.toml` looks like this:
```
std = "roblox"
```

**Comment by chriscerie** [comment] 2023-11-12 17:54
Dupe of #348

**Closed by chriscerie** 2023-11-12 17:54 UTC
