### ISSUE TITLE
`unused_variable` false positive

### ISSUE THREAD

**Issue by ketrab2004** [Kampfkarren/selene#504] opened 2023-04-06 09:45 UTC
When using a function before it's defined it thinks that it isn't used.

```lua
doSomething()

function doSomething() -- doSomething is defined, but never used selene::unused_variable
    print("something")
end
```
In regular lua this would error but in luau this works just fine.

**Comment by Kampfkarren** [comment] 2023-04-07 07:09
> In regular lua this would error but in luau this works just fine.

That isn't true for your code in specific. Luau doesn't change this behavior at all.

That being said, you are roughly right about the bug, this is a duplicate of #212

**Closed by Kampfkarren** 2023-04-07 07:09 UTC

**Comment by ketrab2004** [comment] 2023-04-07 23:39
That is odd, because for me in 5.4 and 5.3 it does error, but not with luau.

`input:1: attempt to call a nil value (global 'doSomething')`

**Comment by Kampfkarren** [comment] 2023-04-08 06:54
![image](https://user-images.githubusercontent.com/3190756/230707898-357656d4-679f-4150-8352-c877455c0c45.png)

**Comment by ketrab2004** [comment] 2023-04-10 14:14
Oh wait my minimal reproducible example is wrong.
```lua
function main()
    doSomething()
end

function doSomething() -- doSomething is defined, but never used selene::unused_variable
    print("something")
end

main()
```
