### ISSUE TITLE
Fix `selene::unused_variable` when using module for Luau types

### ISSUE THREAD

**Issue by vocksel** [Kampfkarren/selene#305] opened 2021-10-09 17:53 UTC
I export types from a `types.lua` ModuleScript, and when I import the module and use my types Selene marks the `types` variable as being unused

![image](https://user-images.githubusercontent.com/3081936/136669158-e48d2f50-d449-422c-beed-f5058df33d50.png)

**Comment by Kampfkarren** [comment] 2021-10-09 22:21
Oh, this is a duplicate of #270, I misread the title.

**Closed by Kampfkarren** 2021-10-09 22:21 UTC
Labels: C-enhancement, A-lints, A-roblox
