### ISSUE TITLE
Incorrect shadowing `self` lint with empty if-else statements

### ISSUE THREAD

**Issue by ok-nick** [Kampfkarren/selene#227] opened 2021-04-13 16:40 UTC
![image](https://user-images.githubusercontent.com/25470747/114588903-2d3c1e80-9c55-11eb-89a9-23e8e26596b5.png)
```lua
local Object = {}

function Object:foo()
	if true then
	else
	end
end

function Object:bar()
end
```

![image](https://user-images.githubusercontent.com/25470747/114589055-4cd34700-9c55-11eb-81fd-2e96f603f02d.png)
```lua
local Object = {}

function Object:foo()
	if true then
	end
end

function Object:bar()
end
```

**Comment by Kampfkarren** [comment] 2021-04-13 16:50
Duplicate of https://github.com/Kampfkarren/selene/issues/116

**Closed by Kampfkarren** 2021-04-13 16:50 UTC
