### ISSUE TITLE
Add "`not X == Y` is equivalent to `(not X) == Y`" lint

### ISSUE THREAD

**Issue by Nidoxs** [Kampfkarren/selene#498] opened 2023-03-19 22:15 UTC
(Not my image, taken from a fellow OSS server member.)
![image](https://user-images.githubusercontent.com/75750304/226212837-29e1a22a-e3cb-4199-8a67-799dce13bf4e.png)

**Comment by chriscerie** [comment] 2023-10-26 02:23
Dupe of #286

**Closed by chriscerie** 2023-10-26 02:23 UTC
Labels: C-enhancement, A-lints
