### ISSUE TITLE
standard library function `Instance.new` requires 1 parameters, 2 passed

### ISSUE THREAD

**Issue by xc0ff33** [Kampfkarren/selene#495] opened 2023-03-04 14:25 UTC
The Roblox Lua function Instance.new seems to require one parameter, but in my code I had two. I think that Selene should support dual arguments for this function, as they do exist and can run in Roblox (instance type, parent).

Selene doesn't yet support this.
![Screenshot 2023-03-04 072445](https://user-images.githubusercontent.com/126925753/222907852-fd4ed4fb-058f-4e9e-96bd-c121f1edd434.png)
![Screenshot 2023-03-04 072529](https://user-images.githubusercontent.com/126925753/222907887-25370ff2-7677-4c19-a9d2-878b2ee928fd.png)

**Comment by Kampfkarren** [comment] 2023-03-04 22:33
The second parameter is officially deprecated. You should not use it. There is no case where it's fine because of this.

The closest that this will be adjusted is #433.

Duplicate of:
#114
#115
#121
#280
#378
#478

**Closed by Kampfkarren** 2023-03-04 22:33 UTC
