### ISSUE TITLE
Warn against lint docs that do not appear in SUMMARY.md

### ISSUE THREAD

**Issue by chriscerie** [Kampfkarren/selene#514] opened 2023-04-23 21:56 UTC
A test for this would prevent issues like in #513.

Perhaps warning against lints that do not have corresponding docs would be good as well, but would false positive in the case of personal lints.

**Comment by Kampfkarren** [comment] 2023-04-24 06:07
Dupe of #365

**Closed by Kampfkarren** 2023-04-24 06:07 UTC
