### ISSUE TITLE
script arguments (vararg) is not defined

### ISSUE THREAD

**Issue by Jayrgo** [Kampfkarren/selene#165] opened 2020-10-16 18:42 UTC
```
error[undefined_variable]: `...` is not defined

   ┌── AddOn.lua:1:26 ───
   │
 1 │ local AddOnName, AddOn = ...
   │                          ^^^
   │
```

The entire vararg holds the arguments passed to the script.

**Comment by Kampfkarren** [comment] 2020-10-16 18:47
Duplicate of #124.

**Closed by Kampfkarren** 2020-10-16 18:47 UTC
