### ISSUE TITLE
Request: Lint for coroutines that are created but never run

### ISSUE THREAD

**Issue by Elttob** [Kampfkarren/selene#278] opened 2021-07-26 18:31 UTC
To be specific about where this is useful, consider the following code snippet, which intends to create and run a coroutine using `coroutine.wrap`:

```Lua
coroutine.wrap(function()
	STEP_EVENT:Wait()

	if isDisconnected then
		return
	elseif not ancestryChangedConn.Connected then
		-- ...snip for conciseness...
		cleanup(task)
		disconnect()
	end
end)
```

However, this coroutine never runs, because the function returned from `coroutine.wrap` is not invoked. To fix the above snippet, a pair of parentheses at the end is required: `coroutine.wrap(func)()` as opposed to `coroutine.wrap(func)`.

This is a very subtle and hard to spot omission, because the end of a `coroutine.wrap()` statement can often be quite far from the start, as in the snippet above. For that reason, adding a lint for this would be especially beneficial.

It could perhaps also extend to a few other ways of creating and running coroutines, depending on how involved you'd want to get.

**Comment by Kampfkarren** [comment] 2021-07-26 19:27
Duplicate of #266, though with a new function, I'll make sure to tag this as well.

**Closed by Kampfkarren** 2021-07-26 19:27 UTC

**Comment by zovits** [comment] 2021-07-26 20:01
Is it a duplicate? This request is about catching unrun coroutines, not simply unread returns.
Catching unread return values wouldn't cover a coroutine that is created, read and stored, but never passed to resume.

**Comment by Kampfkarren** [comment] 2021-07-26 20:56
Yes, it is the same thing. `coroutine.wrap`'s result would be tagged as must use.

>  Catching unread return values wouldn't cover a coroutine that is created, read and stored, but never passed to resume.

I don't think it's common to be storing a coroutine *and* read it *and* not run it *and* in a way selene could inspect statically.
