### ISSUE TITLE
False positive when using methods on constant userdata values in the standard library

### ISSUE THREAD

**Issue by ambergamefam** [Kampfkarren/selene#592] opened 2024-03-21 22:21 UTC
The following line of code emits a false positive "incorrect standard library use" warning:
```lua
local zAxis = Vector3.xAxis:Cross(Vector3.yAxis)
```
<img width="860" alt="image" src="https://github.com/Kampfkarren/selene/assets/122126644/b5c65d24-f266-4841-802e-d1b75699912a">

I was able to work around this warning by wrapping `Vector3.xAxis` in parentheses
```lua
    local facingVector = (Vector3.xAxis):Cross(floorCast.Normal)
```

**Comment by chriscerie** [comment] 2024-03-22 05:03
Dupe of #348.

**Closed by chriscerie** 2024-03-22 05:03 UTC
