### ISSUE TITLE
Incorrect standard library use on Instance.new

### ISSUE THREAD

**Issue by Limeception** [Kampfkarren/selene#478] opened 2023-01-05 17:48 UTC
<img width="484" alt="Screenshot 2023-01-05 at 10 43 57 AM" src="https://user-images.githubusercontent.com/114687251/210845807-b22f1548-27f7-48cf-8081-f82174e703df.png">
<img width="815" alt="Screenshot 2023-01-05 at 10 44 35 AM" src="https://user-images.githubusercontent.com/114687251/210845910-b2df5567-ec5a-4ef0-9520-aecd31c759cb.png">

Selene is marking this as incorrect standard library use, but Instance.new is able to take the 2nd variable as the Parent. (I am also aware of the PSA to stop using the 2nd variable, but since I am not changing any properties of the Animator, it should be fine.)

**Comment by Kampfkarren** [comment] 2023-01-05 20:57
The second parameter is officially deprecated. You should not use it. There is no case where it's fine because of this.

The closest that this will be adjusted is #433.

Duplicate of:
#114
#115
#121
#280
#378

**Closed by Kampfkarren** 2023-01-05 20:57 UTC
Labels: duplicate
