### ISSUE TITLE
@ and $ cancels linting in a file and isn't expressed through the extension

### ISSUE THREAD

**Issue by ok-nick** [Kampfkarren/selene#207] opened 2021-02-03 22:08 UTC
![G75zzVo4T2](https://user-images.githubusercontent.com/25470747/106815821-6eef8e00-6642-11eb-8b0e-dbf485683e88.gif)

**Comment by Kampfkarren** [comment] 2021-02-04 00:53
Parsing errors cancelling all linting isn't a bug, but selene not telling you the problem is the @/$ sign is.

**Comment by Kampfkarren** [comment] 2021-05-04 17:12
Duplicate of #76

**Closed by Kampfkarren** 2021-05-04 17:12 UTC
Labels: A-vscode, C-bug
