### ISSUE TITLE
Errors on offline startup with the vscode extension

### ISSUE THREAD

**Issue by ghost** [Kampfkarren/selene#174] opened 2020-11-06 21:07 UTC
Getting 2 errors when trying to start the selene vscode extension when offline:

![image](https://user-images.githubusercontent.com/65620355/98414811-58a25800-207c-11eb-9362-07fb92781da7.png)

**Comment by Kampfkarren** [comment] 2020-11-07 00:10
Does the rest of the extension continue to work?

**Comment by Kampfkarren** [comment] 2021-05-04 17:12
Duplicate of #73

**Closed by Kampfkarren** 2021-05-04 17:12 UTC
Labels: A-vscode
