### ISSUE TITLE
CFrame.identify not inheriting proper mehods

### ISSUE THREAD

**Issue by noahrepublic** [Kampfkarren/selene#560] opened 2023-10-11 23:34 UTC
When trying to use CFrame.identity it doesn't seem it inherits properly.

Example:
```
 CFrame.identity:ToObjectSpace(part:GetPivot())
```

Error: standard library global `CFrame.identify` does not contain field `ToObjectSpace`

**Comment by chriscerie** [comment] 2023-10-11 23:53
Dupe of #348.

**Closed by chriscerie** 2023-10-11 23:53 UTC
